### ISSUE TITLE
[Bug] Missing schema key in ~/.sheetwork/profiles.yml

### ISSUE THREAD

**Issue by virvirlopez** [bastienboutonnet/sheetwork#201]
**Is your feature request related to a problem? Please describe.**
Missing the key schema in profiles.yml.

**Describe the solution you'd like**
Add the key into the file.

**Comment by bastienboutonnet** [comment]
It looks like `sheetwork init` doesn't create any content of the profile.yml file at the minute. The only place I found an example is in the documentation that did not have a schema entry so I updted this. 

I'll close the issue as I thiink it's resolveed.
